### PR TITLE
Milestone 5: Style

### PR DESCRIPTION
**Pull request by kubilaycaglayan**
Dear TSE :wave: 

[HEROKU](https://tk-bookstore.herokuapp.com/) :link: 
[README](https://github.com/kubilaycaglayan/bookstore/blob/milestone_5_style/README.md) :spiral_notepad: 

:art: We have used the Zeplin Design to finish our project.

With all my respect... :pray:

### CODE REVIEW

**Review by suretrust — CHANGES_REQUESTED** [review]
Hi team, 👋 

### Great job thus far! 🙌 Please see my comments. 👇 

- [x] Let's get rid of the vertical scroll, your app should be well centered by default without needing to scroll vertically.
Screenshot 2020-09-17 at 12 23 33

- [x] When adding a new book, even though it adds successfully with the chosen category, the select input doesn't change when another category is chosen.
Screenshot 2020-09-17 at 12 26 39

**KIndly submit another CRR once these issues have been solved.** _Happy coding!_ 🎉

**Comment by tirthajyoti-ghosh** [comment]
Thank you so much @suretrust for the review.

Please note that the live version is **not** updated.

**Comment by kubilaycaglayan** [comment]
> Thank you so much @suretrust for the review.
> 
> Please note that the live version is **not** updated.

The latest changes have been released now :blush:

**Review by suretrust — APPROVED** [review]
Hi team, 👋 

### Great job implementing the suggested changes. 🙌 Let's get this merged! 👍

_Good luck with your future projects and happy coding!_ 🎉

**Pull request merged**
